<?php

use \Drupal\Core\Form\FormStateInterface;
use \Drupal\node\NodeInterface;

function klin_general_form_node_form_alter(&$form, FormStateInterface $form_state, $form_id)
{
    if ($form_id === 'node_customer_form') {
        $form['title'] = [
            '#type' => 'hidden',
            '#value' => hash('md5', time())
        ];
    } elseif ($form_id === 'node_order_form') {
        $form['title'] = [
            '#type' => 'hidden',
            '#value' => 'Order #'
        ];
    }
}

function klin_general_node_insert(NodeInterface $node)
{
    if ($node->bundle() === 'order') {
        $node->set('title', $node->get('title')->getValue()[0]['value'].' '.$node->id());
        $node->save();
    }
}
